sudo: required

# choose trusty for nvidia-cuda-toolkit
dist: trusty

language: cpp

compiler: gcc

before_install:
  # cuda libraries will be in multiverse
  - sudo apt-add-repository multiverse
  # update before start
  - sudo apt-get update -qq

install:
  # install nvcc
  - sudo apt-get install -qq -y nvidia-cuda-toolkit

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VLPNLl9uAs4/Sv1yGKb3O24jRNEDutux2wxzfb+NUulWUHTGC5R40CbBfFVUzNdVTVPN2T1BBSsl6aFXgwTq1tM7QsqSYAiJkz/LeLnkeR7sdGEg/ffFJnV5sV/9tLkCLeSQoxIupYjV5VYickePd9keHlHpLDrBr5+StijvpUfeGRuLDNjqOQjw3e5F6GBpbA0k0cCC2mZy0qkur/nWzFzqYsmPkJfLKAAPYHFVnwxFyLcFT1pIown6+tWfCapAhybGF/FNteumYkBxa6d08l1ghg8dnrkh+fBreyIISBGxNsJuxS/xyYfi/o1XHVakpSkJCiAEd99HjamXSx25sUb0wB/gCebbRD+EndwY6oOWawD256zJCp1i4X9cCPbhIOFl+glCXvxzdwkDziRUwgaUYKUZPegmdnk2jpCXEkn43WHMb6KQ4XtAu3wLqlE/5NHP8ftX4jWTbTXWA/WpSn6xEmzMf8oH51A/5Jjc/4bd1rzOMX1qf5LukNTfYv7dYsxkEoAtDYN5X27ALgUf1GMUfZfWzf6cJPl6M7b8TJ0a1s3nTNuvHvGeFZhk0K1wFyj7uL38rAWX+lWWFsYjKgzkLRmBl+z25MYpS9GNDosWLyveJmGL5CYCbzQo+K5sJo+4c72Iiq4fSrbmkjSTMHw6SADpbh1WZJY1mKff3p0="

addons:
  coverity_scan:
    project:
      name: "sifaserdarozen/DDGen"
      description: "Build submitted via Travis CI"
    notification_email: sifa.serdar.ozen@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

script:
  # make ddgen and corresponding unit tests ddgen_utests
  - make
  
  # run catch unit tests
  - ./bin/ddgen_utests
