[
    {
        "ParameterKey": "EnvironmentName",
        "ParameterValue": "ddgen"
    },
    {
        "ParameterKey": "AppName",
        "ParameterValue": "ddgen"
    },
    {
        "ParameterKey": "VpcCIDR",
        "ParameterValue": "10.0.0.0/16"
    },
    {
        "ParameterKey": "PublicSubnetDDGenCIDR",
        "ParameterValue": "10.0.0.0/24"
    },
    {
        "ParameterKey": "PublicSubnetMockRecorderCIDR",
        "ParameterValue": "10.0.1.0/24"
    },
    {
        "ParameterKey": "InstanceType",
        "ParameterValue": "t2.micro"
    },
        {
        "ParameterKey": "DesiredCapacity",
        "ParameterValue": "1"
    },
    {
        "ParameterKey": "MaxSize",
        "ParameterValue": "2"
    }
]
