apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddgen
  labels:
    app: ddgen
spec:
  selector:
    matchLabels:
      app: ddgen
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ddgen
    spec:
      containers:
      - name: ddgen
        image: {{default "sifaserdarozen/ddgen:latest" .Values.image}}
        env:
        - name: IMAGE
          value: {{default "sifaserdarozen/ddgen:latest" .Values.image}}
        command: ["./ddgen"]
        args: ["--webConfig"]
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
