apiVersion: v1
kind: Service
metadata:
  name: ddgen
  labels:
    app: ddgen
spec:
  selector:
    matchLabels:
      app: ddgen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
