apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddgen25
  labels:
    app: ddgen25
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddgen25
  template:
    metadata:
      labels:
        app: ddgen25
    spec:
      containers:
      - name: ddgen25
        image: sifaserdarozen/ddgen:latest
        command: ["./ddgen"]
        args: ["--nc", "2", "--dc", "60", "--mirror", "--socket", "172.17.0.2", "28008", "--start", "172.25.201.54"]